
mybatis.mapper-locations=classpath:com/bjpowernode/seckill/mapper/*.xml


spring.datasource.driver-class-name=com.mysql.jdbc.Driver
spring.datasource.url=jdbc:mysql://192.168.31.128:3306/seckill?useUnicode=true&characterEncoding=utf8&useSSL=false
spring.datasource.username=root
spring.datasource.password=123456



spring.activemq.broker-url=tcp://192.168.31.128:61616

#开发阶段，建议关闭thymeleaf的缓存
spring.thymeleaf.cache=false
#使用遗留的html5以去掉对html标签的校验
spring.thymeleaf.mode=LEGACYHTML5

server.port=80



